#31 user story welcoming block
WebUI-Project-Based-07-nr/Client pull request #128
Opened 2024-07-24 10:36 UTC by mistercapxx

![Screenshot 2024-07-24 at 13 18 51](https://github.com/user-attachments/assets/0fc3b841-80e4-42c6-9934-53b3dab58e94)
![Screenshot 2024-07-24 at 13 18 33](https://github.com/user-attachments/assets/cf49508e-0cb0-4f0e-9d27-e3d8124ae806)
Worked on button animation, on reaction if we click on it. Worked with mobile adaptive part. Made description block move while world map remains on same position.

2024-07-25 14:20 UTC, CallMeMaverick reviewed
![image](https://github.com/user-attachments/assets/ebf88539-eb42-4e76-8c3a-ead38a175bdb)

Two issues in sonar, perhaps those should be addressed

2024-07-26 12:35 UTC, markgol777 requested changes
The unit testing for SearchInput was not part of the task

2024-07-26 12:42 UTC, miller-113 commented on src/components/accordion/Accordion.styles.ts
Need to correct formatting
<img width="880" alt="Screenshot 2024-07-26 at 15 41 34" src="https://github.com/user-attachments/assets/6e0df979-c676-4d04-bcfc-99bfc4b8ffe5">
 
<img width="1058" alt="Screenshot 2024-07-26 at 15 42 23" src="https://github.com/user-attachments/assets/b9fa1f5a-a076-4673-a255-c02010cbb233">

2024-07-26 12:45 UTC, miller-113 commented on src/components/accordion/Accordions.tsx
Why in this case you using destructurization? 
<img width="981" alt="Screenshot 2024-07-26 at 15 43 43" src="https://github.com/user-attachments/assets/4ea3f41a-5766-4dc5-a94d-343430dca63c">

2024-07-26 12:56 UTC, miller-113 reviewed
Files need reformatting. The best way to achieve this using prettier

2024-07-26 12:56 UTC, miller-113 commented on src/components/accordion-with-image/AccordionWithImage.styles.ts
formatting

2024-07-26 12:56 UTC, miller-113 commented on src/components/accordion-with-image/AccordionWithImage.tsx
formatting. Too much space between return.

2024-07-26 12:56 UTC, miller-113 commented on src/components/carousel-with-image/CarouselWithImage.styles.ts
formatting

2024-07-26 12:56 UTC, miller-113 commented on src/components/carousel-with-image/CarouselWithImage.tsx
formatting

2024-07-26 12:56 UTC, miller-113 commented on src/containers/guest-home-page/styles/Welcome.styles.ts
formatting and u left commented line.

2024-07-26 12:56 UTC, miller-113 commented on src/pages/guest-home-page/GuestHome.tsx
<img width="482" alt="Screenshot 2024-07-26 at 15 52 35" src="https://github.com/user-attachments/assets/d7e5e69f-fbd1-4c5f-a69d-392e751cbc5d">

formatting, it's must look line in the screenshot

2024-07-26 13:07 UTC, Yaroslav-Yakovlev approved these changes

2024-07-29 13:19 UTC, miller-113 approved these changes
👍

2024-07-29 14:18 UTC, CallMeMaverick approved these changes

2024-08-01 18:39 UTC, markgol777 approved these changes

2024-08-05 07:52 UTC, nrevutska approved these changes

2024-08-05 09:04 UTC, merged