Feature/103/general info
WebUI-Project-Based-07-nr/Client pull request #134
Opened 2024-07-26 09:30 UTC by mistercapxx

#103 - General Info Step for localhost student and tutor
<img width="1034" alt="Screenshot 2024-07-25 at 21 43 58" src="https://github.com/user-attachments/assets/f709e029-efbd-41e4-8fc8-7377726a0fc6">
![Screenshot 2024-07-26 at 12 30 26](https://github.com/user-attachments/assets/3b8da85d-ff75-48b3-8163-3e08a9d93297)

2024-07-26 12:37 UTC, markgol777 requested changes
Too many changes and most of them do not correspond to the task

2024-07-26 12:58 UTC, Yaroslav-Yakovlev approved these changes

2024-07-29 13:22 UTC, markgol777 approved these changes
amazing

2024-07-29 13:27 UTC, Yaroslav-Yakovlev commented
The screenshot does not match the layout
![Screenshot_3](https://github.com/user-attachments/assets/6a451d09-4f8f-4b15-9f22-4cf48e78acf4)

2024-07-29 20:48 UTC, Bakalina approved these changes

2024-08-02 11:41 UTC, mistercapxx commented
![Screenshot 2024-08-02 at 14 37 39](https://github.com/user-attachments/assets/a5542ecb-4d50-46dc-9723-e512812b5911)
made it fine looking

2024-08-02 11:45 UTC, CallMeMaverick commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
> +  const countryCityMap = {
I think there is a backend task to fetch countries and respective cities #94 
So I believe this logic is redundant

2024-08-02 14:53 UTC, Yaroslav-Yakovlev approved these changes

2024-08-03 13:10 UTC, CallMeMaverick approved these changes

2024-08-04 12:51 UTC, kryzanivska-nastya approved these changes

2024-08-05 07:57 UTC, nrevutska approved these changes
Create a new task to connect this with backend and implement it.

2024-08-05 09:04 UTC, merged