Feature/164/implement offer card
WebUI-Project-Based-07-nr/Client pull request #173
Opened 2024-08-01 21:44 UTC by miller-113

Implemented offer card & square card into the project
issues: 
Author's avatar and name redirects to the home page as the author's profile does not exist yet
Add my list button has not been implemented yet as wish list component does not exist yet

2024-08-04 20:26 UTC, Bakalina approved these changes

2024-08-05 11:52 UTC, CallMeMaverick approved these changes

2024-08-05 15:50 UTC, nrevutska requested changes
there are many files changed, check if all of the changes belong to this pull request

2024-08-05 15:50 UTC, nrevutska commented on src/pages/offer-details/OfferDetails.tsx
> +  // }
this comment shouldn't be here

2024-08-05 15:50 UTC, nrevutska commented on src/pages/offer-details/OfferDetails.tsx
> +// import { useModalContext } from '~/context/modal-context'
remove this comment

2024-08-05 17:32 UTC, nrevutska approved these changes

2024-08-05 17:59 UTC, merged