bold weight erased
WebUI-Project-Based-07-nr/Client pull request #186
Opened 2024-08-04 12:46 UTC by mistercapxx

![Screenshot 2024-08-04 at 15 44 07](https://github.com/user-attachments/assets/42eda00a-aa88-4958-967f-1d2a2d38d9d3)
bold weight is deleted now

2024-08-04 12:53 UTC, kryzanivska-nastya approved these changes

2024-08-04 20:22 UTC, Bakalina approved these changes

2024-08-04 20:50 UTC, CallMeMaverick approved these changes

2024-08-04 22:32 UTC, markgol777 commented
this task has already been completed?

2024-08-05 09:07 UTC, mistercapxx commented
> this task has already been completed?

no bro as bold font been present

2024-08-05 13:47 UTC, Yaroslav-Yakovlev approved these changes

2024-08-06 12:56 UTC, nrevutska requested changes

2024-08-06 12:56 UTC, nrevutska commented on src/components/title-with-description/TitleWithDescription.styles.ts
> +    fontWeight: 'normal'
where this style is used now (you removed it from the TitleWithDescription component and now it probably is not used anywhere)

2024-08-07 17:00 UTC, nrevutska approved these changes

2024-08-08 15:26 UTC, merged