Feature/229/implement edit for lessons
WebUI-Project-Based-07-nr/Client pull request #250
Opened 2024-08-13 11:00 UTC by Bakalina

https://github.com/user-attachments/assets/d56a701d-78fe-4d1e-91dd-0cfbbf6f6c62

2024-08-13 12:27 UTC, miller-113 requested changes
caught you using chatgpt:) NOTE: please remove chatgpt comments ty

2024-08-13 12:28 UTC, mistercapxx commented
https://giphy.com/gifs/seijioda-caught-you-found-out-horny-police-PVTPhCDvNlUfJRBoZ9

2024-08-13 16:30 UTC, Yaroslav-Yakovlev approved these changes

2024-08-14 09:53 UTC, kryzanivska-nastya approved these changes

2024-08-14 17:11 UTC, nrevutska approved these changes

2024-08-14 20:47 UTC, merged