fixed
WebUI-Project-Based-07-nr/Client pull request #49
Opened 2024-07-11 10:14 UTC by markgol777

2024-07-15 09:16 UTC, mistercapxx approved these changes

2024-07-15 09:18 UTC, CallMeMaverick approved these changes

2024-07-15 09:21 UTC, Bakalina approved these changes

2024-07-15 12:32 UTC, Yaroslav-Yakovlev approved these changes

2024-07-16 15:52 UTC, nrevutska requested changes
the task linked to this pr does not correspond to the changes that were made

2024-07-16 15:52 UTC, nrevutska commented on src/containers/guest-home-page/login-form/LoginForm.jsx
> +
we cannot leave these comments in the code

2024-07-16 15:52 UTC, nrevutska commented on tsconfig.json
> +    "jsx": "preserve",
why this change was made and how is it related to the task?

2024-07-16 19:01 UTC, markgol777 commented on src/containers/guest-home-page/login-form/LoginForm.jsx
> +
sorry forgot to remove

2024-07-16 19:20 UTC, markgol777 commented on tsconfig.json
> +    "jsx": "preserve",
I kept getting compiling errors so I was forced to change it

2024-07-17 20:42 UTC, nrevutska approved these changes

2024-07-17 20:44 UTC, merged