Pop up button disabled fix
WebUI-Project-Based-07-nr/Client pull request #53
Opened 2024-07-12 05:46 UTC by markgol777

2024-07-15 12:33 UTC, Yaroslav-Yakovlev approved these changes

2024-07-15 13:28 UTC, Bakalina approved these changes

2024-07-15 16:38 UTC, Yaroslav-Yakovlev approved these changes

2024-07-16 09:17 UTC, mistercapxx approved these changes

2024-07-16 09:22 UTC, miller-113 approved these changes

2024-07-16 09:35 UTC, CallMeMaverick approved these changes

2024-07-18 06:47 UTC, nrevutska requested changes
let's try to pass the quality gate
![image](https://github.com/user-attachments/assets/6a6311a8-2bdb-4315-8c2d-bff84b2efa1b)

2024-07-18 06:47 UTC, nrevutska commented on src/containers/guest-home-page/login-form/LoginForm.jsx
> +  const passwordRef = useRef(null)
Why do we need these refs?

2024-07-18 11:23 UTC, markgol777 commented on src/containers/guest-home-page/login-form/LoginForm.jsx
> +  const passwordRef = useRef(null)
removed

2024-07-24 15:18 UTC, nrevutska approved these changes

2024-07-30 21:17 UTC, merged