Test for chips-list component
WebUI-Project-Based-07-nr/Client pull request #69
Opened 2024-07-15 11:52 UTC by kryzanivska-nastya

## Description
The onDelete={handleDelete} prop is added to the Chip component to ensure that the delete functionality works correctly

Test cases: 
- [ ] it should show chips
- [ ] it should show chip with +3
- [ ] it should show only 7 chips
- [ ] it should show only 10 chips
- [ ] it should delete 1 chip

## Screenshots
![msg816281288-346864 000002](https://github.com/user-attachments/assets/d93aa759-3f74-41ef-88ef-5c9e1ca48088)

2024-07-15 12:30 UTC, Yaroslav-Yakovlev approved these changes

2024-07-15 13:27 UTC, Bakalina approved these changes

2024-07-16 09:29 UTC, miller-113 approved these changes

2024-07-17 13:42 UTC, nrevutska requested changes
Also please, make sure that there is no other option available where *byTestId is used

2024-07-17 13:42 UTC, nrevutska commented on src/tests/unit/components/app-chip-list/AppChipList.spec.jsx
> +    const showMoreElement = screen.queryByText(`+${mockItems.length - 2}`)
better to use another query variant here:
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library
![Uploading image.png…]()

2024-07-18 10:00 UTC, nrevutska approved these changes

2024-07-18 10:01 UTC, merged