Wrote tests for search input component
WebUI-Project-Based-07-nr/Client pull request #70
Opened 2024-07-15 19:20 UTC by Yaroslav-Yakovlev

Write tests for search filter input component

![Screenshot_5](https://github.com/user-attachments/assets/0c174d0f-cbae-47ea-9b8f-25425948699a)

2024-07-16 06:50 UTC, kryzanivska-nastya approved these changes

2024-07-16 09:34 UTC, miller-113 approved these changes

2024-07-16 09:35 UTC, CallMeMaverick approved these changes

2024-07-16 09:46 UTC, Bakalina approved these changes

2024-07-16 15:59 UTC, nrevutska requested changes
It is better to use userEvent in place of fireEvent
https://testing-library.com/docs/user-event/intro/#difference-to-fireevent
![image](https://github.com/user-attachments/assets/042e16ed-b7b7-4c85-be4e-78303d356cb9)

2024-07-17 12:18 UTC, Yaroslav-Yakovlev commented
Repleted fireEvent method to userEvent

2024-07-17 12:45 UTC, nrevutska approved these changes

2024-07-17 13:29 UTC, merged