Write tests for content switcher component #57
WebUI-Project-Based-07-nr/Client pull request #71
Opened 2024-07-16 07:15 UTC by Bakalina

Create tests for AppContentSwitcher component
![Знімок екрана 2024-07-16 035150](https://github.com/user-attachments/assets/fcfa6fbc-b015-40b8-b3ec-55fb9abe01aa)

2024-07-16 09:18 UTC, Yaroslav-Yakovlev approved these changes

2024-07-16 09:18 UTC, kryzanivska-nastya approved these changes

2024-07-16 09:58 UTC, miller-113 approved these changes
👍

2024-07-17 10:24 UTC, Yaroslav-Yakovlev approved these changes

2024-07-17 21:11 UTC, nrevutska requested changes
use userEvent where possible

2024-07-17 21:11 UTC, nrevutska commented on src/tests/unit/components/app-content-switcher/AppContentSwitcher.spec.jsx
> +    fireEvent.click(switchElement)
we should prefer userEvent vs fireEvent where it is possible
https://testing-library.com/docs/user-event/intro/#difference-to-fireevent
![image](https://github.com/user-attachments/assets/0d92616a-7ac8-4932-931c-af2ff1214441)

2024-07-18 10:23 UTC, nrevutska approved these changes

2024-07-18 10:36 UTC, merged