create tests for UserStepsWrapper
WebUI-Project-Based-07-nr/Client pull request #73
Opened 2024-07-17 10:22 UTC by Bakalina

Create tests for UserStepsWrapper component
![Знімок екрана 2024-07-17 130553](https://github.com/user-attachments/assets/6c3fdcdd-39a3-4adb-ad04-e83d02b24237)

2024-07-17 12:50 UTC, kryzanivska-nastya approved these changes

2024-07-18 10:14 UTC, Yaroslav-Yakovlev approved these changes

2024-07-19 07:25 UTC, kryzanivska-nastya approved these changes

2024-07-19 12:21 UTC, CallMeMaverick approved these changes

2024-07-22 15:40 UTC, nrevutska requested changes
please change using fireEvent to userEvent
https://testing-library.com/docs/user-event/intro#differences-from-fireevent
![image](https://github.com/user-attachments/assets/466ea13f-d9c4-4c46-babd-f60db8057f58)
Also, your mock should not contain conditional constructions, create as simple mock as possible. Create two simpler mocks if needed

2024-07-22 18:53 UTC, CallMeMaverick approved these changes

2024-07-24 15:22 UTC, nrevutska approved these changes

2024-07-24 16:23 UTC, merged