Test/64/test sliderinput
WebUI-Project-Based-07-nr/Client pull request #85
Opened 2024-07-18 17:44 UTC by mistercapxx

#64 - Slider With Input tests ready

2024-07-19 07:58 UTC, Yaroslav-Yakovlev reviewed
You can use beforeEach method in describe block to configure the state of execution of each test.

2024-07-19 10:09 UTC, Yaroslav-Yakovlev approved these changes

2024-07-19 11:27 UTC, kryzanivska-nastya approved these changes

2024-07-19 11:28 UTC, miller-113 approved these changes

2024-07-19 11:29 UTC, CallMeMaverick approved these changes

2024-07-19 11:48 UTC, nrevutska requested changes
add awaits everywhere where it is needed

2024-07-19 11:48 UTC, nrevutska commented on src/tests/unit/components/slider-with-input/SliderWithInput.spec.jsx
> +    userEvent.tab()
await is missed here (should be the same as in 38 row)

2024-07-19 13:16 UTC, nrevutska requested changes
fix formatting please
![image](https://github.com/user-attachments/assets/6b50ddde-9026-4bb7-a395-f74049f32bf6)

2024-07-23 12:15 UTC, markgol777 approved these changes
good

2024-07-23 12:15 UTC, markgol777 commented on src/constants/translations/en/guest-home-page.json
I'm pretty sure for the issue linked you didn't need to change this file.

2024-07-23 12:15 UTC, markgol777 commented on src/tests/unit/components/slider-with-input/SliderWithInput.spec.jsx
everything else looks good here

2024-07-29 10:05 UTC, nrevutska approved these changes

2024-07-29 11:23 UTC, merged